#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2020-04-01 16:29:20
# @Author  : Joyce Yang (joyce3.yang@gmail.com)
# @Link    : https://github.com/joyceyj

import os
import sys
import openpyxl

# 打开Excel文件
# filepath 文件路径
def open_excel(filepath):
	try:
		data = openpyxl.load_workbook(filepath)
		return data
	except IOError:
		print("no find: " + filepath)

# 根据Sheet名称获取Excel指定表格中的数据
def get_data_by_name(filepath, sheet_name):
	file = open_excel(filepath)
	try:
		sheet = file[sheet_name]
		return sheet
	except IOError:
		print("no exit: " + sheet_name)

# 复制表格行元组为list
def row_data_type_change(row):
	data = []
	for i in row:
		data.append(i.value)
	return data

# 比较两张表格：根据某一列column_idx的值进行比较
# 返回不同的行数据
def compare_sheet(sheet1, sheet2, column1_idx, column2_idx):
	data = []
	for row1 in sheet1.rows:
		tmp = []
		new_flag = True
		for row2 in sheet2.rows:
			if (row1[column1_idx].value == row2[column2_idx].value):
				new_flag = False
				break
		if (new_flag):
			data.append(row_data_type_change(row1))
	return data

def test():
	document_path = sys.path[0]
	object_file_name = "test1.xlsx"
	filepath = os.path.join(document_path, object_file_name)
	workbook, sheet1 = get_data_by_name(file_path, "excel_data")

if __name__ == '__main__':
	test()
